name: deployment

on:
  workflow_dispatch

jobs:
  deploy-library-rg:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        env:
           CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}
      - uses: actions/checkout@v2
      - run: az deployment sub create --name libraryRgDeploy \
              --location northeurope --template-file deployment/rgdeploy.json \
              --parameters deployment/rgdeploy.parameters.json

  deploy-library:
    needs: deploy-library-rg
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        env:
           CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}
      - uses: actions/checkout@v2
      - run: az deployment group create --name github-library \
          --resource-group LibraryRG \
          --template-file deployment/deploy.json \
          --parameters deployment/deploy.parameters.json