name: teardown

on:
  workflow_dispatch

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        env:
           CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}
      - run: az group delete --name LibraryRG